[package]
name = "data_structures"
version = "1.0.0"
authors = []

[addresses]
data_structures_address ='6688bdce931ec5a9fabb3d92f6a32cbfa80fda5f24e261ffda72a60123ea2dd6'

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
